import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { buildBlogPostDrafts } from './blog-content-generator.mjs';
import { generateBlogHeroImage } from './blog-image-generator.mjs';
import { validateBlogPosts } from './blog-validation.mjs';

const sourcePath = process.env.BLOG_TOPIC_SOURCE_PATH || 'docs/blog-posts-to-do';
const outputPath = resolve(process.cwd(), 'src/data/generated-blog-posts.js');
const slugsOutputPath = resolve(process.cwd(), 'src/data/generated-blog-slugs.js');

export async function seedBlogs({ writeLocalFile = true, syncGcp = true } = {}) {
  const posts = await buildBlogPostDrafts({ sourcePath });
  const images = [];

  for (const post of posts) {
    const image = await generateBlogHeroImage(post);
    post.heroImage = {
      ...post.heroImage,
      url: image.localUrl,
      gcpPath: image.gcpPath,
    };
    post.schemaJsonLd = {
      ...post.schemaJsonLd,
      image: {
        ...post.schemaJsonLd.image,
        url: `https://estospaces.com${image.localUrl}`,
      },
    };
    images.push(image);
  }

  const validation = validateBlogPosts(posts, { expectedCount: 100 });

  if (!validation.valid) {
    throw new Error(`Blog validation failed:\n${validation.errors.join('\n')}`);
  }

  if (writeLocalFile) {
    await mkdir(dirname(outputPath), { recursive: true });
    await writeFile(outputPath, toJsModule(posts), 'utf8');
    await writeFile(slugsOutputPath, toSlugsModule(posts), 'utf8');
  }

  let gcp = {
    created: 0,
    updated: 0,
    skipped: posts.length,
    imagesUploaded: 0,
    imagesSkipped: posts.length,
    reason: 'GCP credentials not configured',
  };

  if (syncGcp && hasGcpConfig()) {
    const { createOrUpdateBlogPost, uploadBlogImage } = await import('../src/lib/blogs.js');
    let updated = 0;
    let imagesUploaded = 0;

    for (const [index, post] of posts.entries()) {
      const upload = await uploadBlogImage({
        slug: post.slug,
        bytes: images[index].bytes,
        contentType: images[index].contentType,
        fileName: images[index].fileName,
      });
      const remotePost = upload.skipped
        ? post
        : {
            ...post,
            heroImage: {
              ...post.heroImage,
              url: upload.url,
              gcpPath: upload.gcpPath,
            },
            schemaJsonLd: {
              ...post.schemaJsonLd,
              image: {
                ...post.schemaJsonLd.image,
                url: upload.url,
              },
            },
          };

      if (!upload.skipped) imagesUploaded += 1;
      const result = await createOrUpdateBlogPost(remotePost);
      if (result?.skipped) continue;
      updated += 1;
    }

    gcp = {
      created: 0,
      updated,
      skipped: posts.length - updated,
      imagesUploaded,
      imagesSkipped: posts.length - imagesUploaded,
      reason: null,
    };
  }

  return {
    sourcePath,
    localOutput: writeLocalFile ? outputPath : null,
    localSlugsOutput: writeLocalFile ? slugsOutputPath : null,
    localImages: images.length,
    total: posts.length,
    categories: [...new Set(posts.map((post) => post.category))].length,
    gcp,
    validation,
  };
}

function hasGcpConfig() {
  return Boolean(
    process.env.GCP_PROJECT_ID &&
    process.env.GCP_CLIENT_EMAIL &&
    process.env.GCP_PRIVATE_KEY &&
    process.env.GCP_BUCKET_NAME,
  );
}

function toJsModule(posts) {
  return [
    '// Generated by scripts/seed-blogs.mjs.',
    '// Do not edit by hand. Update docs/blog-posts-to-do and rerun npm run blogs:seed.',
    `const posts = ${JSON.stringify(posts, null, 2)};`,
    '',
    'export default posts;',
    '',
  ].join('\n');
}

function toSlugsModule(posts) {
  return [
    '// Generated by scripts/seed-blogs.mjs.',
    '// Do not edit by hand.',
    `const slugs = ${JSON.stringify(
      posts.map((post) => post.slug),
      null,
      2,
    )};`,
    '',
    'export default slugs;',
    '',
  ].join('\n');
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  seedBlogs()
    .then((summary) => {
      console.log(JSON.stringify(summary, null, 2));
    })
    .catch((error) => {
      console.error(error);
      process.exit(1);
    });
}
